"""Prometheus SNMP Exporter Datarecipient Plugin

Generates Prometheus SNMP exporter service discovery configuration files.

Plugin Identification: type = "snmp_exporter"

Purpose:
--------
Outputs Prometheus service discovery files for SNMP monitoring.
Creates JSON-formatted target files that Prometheus uses to discover
and scrape SNMP devices via the snmp_exporter.

Configuration:
--------------
INI Format:
    [datarecipient_prometheus]
    type = snmp_exporter
    objects_dir = /etc/prometheus/snmp_targets
    max_delta = 10,20
    max_delta_action = /path/to/rollback_script.sh
    safe_output = yes
    want_tool = prometheus

Parameters:
    objects_dir: Base directory for output files
    static_dir: {objects_dir}/static (for static configs)
    dynamic_dir: {objects_dir}/dynamic (for generated files)
    max_delta: Threshold for object count changes (hosts,services %)
    max_delta_action: Script to run if max_delta exceeded
    safe_output: Enable git rollback on excessive changes
    want_tool: Tool type to filter (default: "prometheus")

Prometheus SNMP Exporter Overview:
----------------------------------
The Prometheus SNMP exporter acts as a proxy between Prometheus
and SNMP devices. This datarecipient generates the service discovery
files that tell Prometheus which SNMP devices to monitor.

Architecture:
    Prometheus → (scrape) → SNMP Exporter → (SNMP query) → Network Device
                             ↑
                             Service Discovery Files (generated by this plugin)

Output File Structure:
----------------------
{dynamic_dir}/
    targets/
        device1.json
        device2.json
        device3.json

Each JSON file contains Prometheus scrape targets for one device.

Example Output File:
--------------------
{
    "targets": ["snmp-exporter:9116"],
    "labels": {
        "__param_target": "192.168.1.1",
        "__param_module": "if_mib",
        "job": "snmp",
        "hostname": "switch01"
    }
}

Prometheus will scrape: http://snmp-exporter:9116/snmp?target=192.168.1.1&module=if_mib

Git Integration:
----------------
If dynamic_dir contains a .git repository, changes are automatically:
    1. Added: git add .
    2. Committed: git commit -m "YYYY-MM-DD-HH-MM-SS N targets"
    3. Analyzed: Log added/removed hosts

This provides version control and audit trail for monitoring changes.

Safety Features - max_delta:
----------------------------
Prevents accidental mass deletion of monitoring targets.

Configuration:
    max_delta = 10,20
        10 = Maximum host change percentage (10%)
        20 = Maximum service change percentage (20%)

Behavior:
    If changes exceed threshold:
        - Log error messages
        - Run max_delta_action script (if configured)
        - If safe_output=yes and .git exists: git reset --hard

This prevents scenarios like:
    - Datasource misconfiguration deleting all hosts
    - Network issues causing empty datasource read
    - Accidental filter clearing thousands of targets

Example max_delta_action Script:
---------------------------------
#!/bin/bash
# Send alert when monitoring config changes too much
echo "Monitoring config change exceeded threshold" | \
    mail -s "ALERT: Coshsh delta exceeded" ops@example.com
exit 0

Directory Structure:
--------------------
/etc/prometheus/snmp_targets/
    static/        ← Manual configurations (not modified)
    dynamic/       ← Generated configurations (modified by coshsh)
        .git/      ← Optional git repository
        targets/   ← Service discovery JSON files
            switch01.json
            router01.json
            firewall01.json

Prometheus Configuration:
-------------------------
Configure Prometheus to read the generated files:

prometheus.yml:
    scrape_configs:
      - job_name: 'snmp'
        file_sd_configs:
          - files:
            - '/etc/prometheus/snmp_targets/dynamic/targets/*.json'
            refresh_interval: 5m

        metrics_path: /snmp
        params:
          module: [if_mib]

        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: snmp-exporter:9116

Template Usage:
---------------
Applications should generate JSON via templates.

Example template (prometheus_snmp.tpl):
    {%- for app in applications %}
    {
        "targets": ["snmp-exporter:9116"],
        "labels": {
            "__param_target": "{{ app.host.address }}",
            "__param_module": "{{ app.snmp_module|default('if_mib') }}",
            "job": "snmp",
            "hostname": "{{ app.host_name }}"
        }
    }
    {% endfor %}

The template should store output in app.config_files:
    app.config_files['prometheus'][hostname + '.json'] = rendered_json

Workflow:
---------
1. cleanup_target_dir(): Remove old dynamic files (preserve .git)
2. prepare_target_dir(): Create target directories
3. output(): Generate JSON files for each application
4. count_after_objects(): Count generated files
5. Check delta: Compare old vs new counts
6. Git commit: Commit changes (if .git exists)
7. Rollback: Revert if delta exceeded (if safe_output enabled)

Delta Calculation:
------------------
The plugin tracks object counts:
    old_objects: File count before generation
    new_objects: File count after generation
    delta_hosts: Percentage change in hosts
    delta_services: Percentage change in services

If delta exceeds max_delta thresholds:
    - Error logged
    - max_delta_action executed
    - Git reset performed (if safe_output=yes)

Use Cases:
----------
SNMP Monitoring:
    - Network switches
    - Routers
    - Firewalls
    - Load balancers
    - UPS devices
    - Environmental sensors

Dynamic Discovery:
    - Automatic target discovery
    - Configuration version control
    - Safe deployment with rollback
    - Audit trail of changes

Classes:
--------
- DatarecipientPrometheusSnmpExporter: Prometheus SNMP SD file generator

Related Plugins:
----------------
- DatarecipientCoshshDefault: Nagios config generator
- DatarecipientDiscard: No-op recipient

Important Notes:
----------------
The plugin uses print() statements for git output (legacy code).
These should ideally use logger.info() but are kept for compatibility.

The analyze_output() method parses git output to extract added/deleted
hosts and log them for auditing purposes.

The item_write_config() method iterates through app.config_files[tool]
and writes each file to the targets directory.

Monitoring Best Practices:
--------------------------
1. Enable git in dynamic_dir for change tracking
2. Set reasonable max_delta thresholds (5-10%)
3. Configure max_delta_action for alerting
4. Test rollback procedures regularly
5. Monitor coshsh execution for errors
6. Review git log periodically for unexpected changes
"""

#!/usr/bin/env python
#-*- coding: utf-8 -*-
#
# Copyright 2010-2012 Gerhard Lausser.
# This software is licensed under the
# GNU Affero General Public License version 3 (see the file LICENSE).

from __future__ import annotations
from typing import Optional, Dict, Any
import os
import re
import shutil
import logging
import time
from subprocess import Popen, PIPE, STDOUT
import coshsh
from coshsh.datarecipient import Datarecipient
from coshsh.util import compare_attr


logger = logging.getLogger('coshsh')


def __dr_ident__(params: Optional[Dict[str, Any]] = None) -> Optional[type]:
    """Identify Prometheus SNMP exporter datarecipient from parameters.

    Args:
        params: Dictionary containing type and other parameters

    Returns:
        DatarecipientPrometheusSnmpExporter class if type matches "snmp_exporter", else None
    """
    if params is None:
        params = {}
    if coshsh.util.compare_attr("type", params, "^snmp_exporter$"):
        return DatarecipientPrometheusSnmpExporter
    return None


class DatarecipientPrometheusSnmpExporter(coshsh.datarecipient.Datarecipient):
    """Prometheus SNMP Exporter service discovery file generator.

    Generates JSON-formatted target files for Prometheus SNMP monitoring
    with optional git integration and safety features.
    """

    def __init__(self, **kwargs: Any) -> None:
        """Initialize Prometheus SNMP exporter datarecipient.

        Args:
            **kwargs: Datarecipient parameters
                - name: Datarecipient name
                - want_tool: Tool type filter (default: "prometheus")
                - objects_dir: Base output directory
                - recipe_objects_dir: Fallback output directory
                - max_delta: Tuple of (host_%, service_%) change thresholds
                - max_delta_action: Script to run on excessive delta
                - safe_output: Enable git rollback on excessive changes

        Attributes Set:
            name: Datarecipient name
            want_tool: Tool filter
            objects_dir: Base output directory
            static_dir: Static config directory
            dynamic_dir: Generated config directory
            max_delta: Change thresholds
            max_delta_action: Rollback script path
            safe_output: Enable safe mode
        """
        super().__init__(**kwargs)
        self.name = kwargs["name"]
        self.want_tool = kwargs.get("want_tool", "prometheus")
        self.objects_dir = kwargs.get("objects_dir", kwargs.get("recipe_objects_dir", "/tmp"))
        self.max_delta = kwargs.get("max_delta", ())
        self.max_delta_action = kwargs.get("max_delta_action", None)
        self.safe_output = kwargs.get("safe_output")
        self.static_dir = os.path.join(self.objects_dir, 'static')
        self.dynamic_dir = os.path.join(self.objects_dir, 'dynamic')

    def prepare_target_dir(self) -> None:
        """Create target directories for output files.

        Creates:
            - dynamic_dir
            - dynamic_dir/targets
        """
        logger.info("recipient %s dynamic_dir %s" % (self.name, self.dynamic_dir))
        try:
            os.mkdir(self.dynamic_dir)
        except Exception:
            # Will not have been removed with a .git inside
            pass
        try:
            os.mkdir(os.path.join(self.dynamic_dir, 'targets'))
        except Exception:
            pass

    def cleanup_target_dir(self) -> None:
        """Remove old generated files from dynamic directory.

        Preserves .git directory for version control.
        Removes all other subdirectories and files.
        """
        if os.path.isdir(self.dynamic_dir):
            try:
                if os.path.exists(self.dynamic_dir + "/.git"):
                    for subdir in [sd for sd in os.listdir(self.dynamic_dir) if sd != ".git"]:
                        logger.info("recipe %s remove dynamic_dir %s" % (self.name, self.dynamic_dir + "/" + subdir))
                        shutil.rmtree(self.dynamic_dir + "/" + subdir)
                else:
                    logger.info("recipe %s remove dynamic_dir %s" % (self.name, self.dynamic_dir))
                    shutil.rmtree(self.dynamic_dir)
            except Exception as e:
                logger.info("recipe %s has problems with dynamic_dir %s" % (self.name, self.dynamic_dir))
                logger.info(e)
                raise e
        else:
            logger.info("recipe %s dynamic_dir %s does not exist" % (self.name, self.dynamic_dir))

    def output(self, filter: Optional[str] = None, want_tool: Optional[str] = None) -> None:
        """Generate Prometheus service discovery files.

        Args:
            filter: Optional filter string (unused)
            want_tool: Tool type filter (overrides self.want_tool)
        """
        want_tool = self.want_tool
        sd_dir = os.path.join(self.dynamic_dir, 'targets')
        for app in self.objects['applications'].values():
            self.item_write_config(app, sd_dir, app.host_name, want_tool)
        self.count_after_objects()
        logger.info("number of files before: %d targets" % self.old_objects)
        logger.info("number of files after:  %d targets" % self.new_objects)
        if self.safe_output and self.too_much_delta() and os.path.exists(self.dynamic_dir + '/.git'):
            save_dir = os.getcwd()
            os.chdir(self.dynamic_dir)
            logger.error("git reset --hard")
            process = Popen(["git", "reset", "--hard"], stdout=PIPE, stderr=STDOUT, universal_newlines=True)
            output, unused_err = process.communicate()
            retcode = process.poll()
            logger.info(output)
            logger.error("git clean untracked files")
            process = Popen(["git", "clean", "-f", "-d"], stdout=PIPE, stderr=STDOUT, universal_newlines=True)
            output, unused_err = process.communicate()
            retcode = process.poll()
            logger.info(output)
            os.chdir(save_dir)
            self.analyze_output(output)
            logger.error("the last commit was revoked")

        elif self.too_much_delta():
            logger.error("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            logger.error("number of hosts changed by %.2f percent" % self.delta_hosts)
            logger.error("number of applications changed by %.2f percent" % self.delta_services)
            logger.error("please check your datasource before activating this config.")
            logger.error("if you use a git repository, you can go back to the last")
            logger.error("valid configuration with the following commands:")
            logger.error("cd %s" % self.dynamic_dir)
            logger.error("git reset --hard")
            logger.error("git checkout .")
            logger.error("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
            if self.max_delta_action:
                logger.error("running command %s" % self.max_delta_action)
                if os.path.exists(self.max_delta_action) and os.path.isfile(self.max_delta_action) and os.access(self.max_delta_action, os.X_OK):
                    self.max_delta_action = os.path.abspath(self.max_delta_action)
                    save_dir = os.getcwd()
                    os.chdir(self.dynamic_dir)
                    process = Popen([self.max_delta_action], stdout=PIPE, stderr=STDOUT, universal_newlines=True)
                    output, errput = process.communicate()
                    retcode = process.poll()
                    logger.error("cmd says: %s" % output)
                    logger.error("cmd warns: %s" % errput)
                    logger.error("cmd exits with: %d" % retcode)
                    os.chdir(save_dir)
                else:
                    logger.error("command %s is not executable. now you're screwed" % self.max_delta_action)

        elif os.path.exists(self.dynamic_dir + '/.git'):
            logger.debug("dynamic_dir is a git repository")

            save_dir = os.getcwd()
            os.chdir(self.dynamic_dir)
            print("git add------------------")
            process = Popen(["git", "add", "."], stdout=PIPE, stderr=STDOUT, universal_newlines=True)
            output, unused_err = process.communicate()
            retcode = process.poll()
            print(output)
            commitmsg = time.strftime("%Y-%m-%d-%H-%M-%S") + " %d targets" % (self.new_objects,)
            if False:
                process = Popen(["git", "diff"], stdout=PIPE, stderr=STDOUT, universal_newlines=True)
                output, unused_err = process.communicate()
                retcode = process.poll()
                logger.debug("the changes are...")
                logger.debug(output)
            print("git commit------------------")
            print("commit-comment", commitmsg)
            process = Popen(["git", "commit", "-a", "-m", commitmsg], stdout=PIPE, stderr=STDOUT, universal_newlines=True)
            output, unused_err = process.communicate()
            retcode = process.poll()
            print(output)
            os.chdir(save_dir)
            self.analyze_output(output)

    def analyze_output(self, output: str) -> None:
        """Analyze git commit output for added/deleted hosts.

        Args:
            output: Git command output string

        Logs:
            Added and deleted host lists from git changes
        """
        add_hosts = []
        del_hosts = []
        for line in output.split("\n"):
            # create mode 100644 hosts/libmbp1.naxgroup.net/host.cfg
            match = re.match(r'\s*create mode.*hosts/(.*)/host.cfg', line)
            if match:
                add_hosts.append(match.group(1))
            # delete mode 100644 hosts/litxd01.emea.gdc/host.cfg
            match = re.match(r'\s*delete mode.*hosts/(.*)/host.cfg', line)
            if match:
                del_hosts.append(match.group(1))
        if add_hosts:
            logger.info("add hosts: %s" % ','.join(add_hosts))
        if del_hosts:
            logger.info("del hosts: %s" % ','.join(del_hosts))

    def count_objects(self) -> int:
        """Count target files in output directory.

        Returns:
            Number of files in dynamic_dir/targets, or 0 on error
        """
        try:
            targets = len([name for name in os.listdir(os.path.join(self.dynamic_dir, 'targets')) if os.path.isfile(os.path.join(self.dynamic_dir, 'targets', name))])
            return targets
        except Exception:
            return 0

    def item_write_config(self, obj: Any, sd_dir: str, objtype: str, want_tool: Optional[str] = None) -> None:
        """Write configuration files for a monitoring object.

        Args:
            obj: Monitoring object (application) with config_files attribute
            sd_dir: Service discovery directory path
            objtype: Object type (unused - no subdirectory created)
            want_tool: Tool type filter (only write files for this tool)
        """
        # Without objecttype, no automatic intermediate layer "hosts" etc.
        for tool in obj.config_files:
            if not want_tool or want_tool == tool:
                for file in obj.config_files[tool]:
                    content = obj.config_files[tool][file]
                    with open(os.path.join(sd_dir, file), "w") as f:
                        f.write(content)
